### ISSUE TITLE
MBT build in Project with NPM Workspaces fails to use local dependencies

### ISSUE THREAD

**Issue by BenReim** [SAP/cloud-mta-build-tool#1048]
**Issue**
When running a npm script through `mtb` in a project with npm workspaces, the local node dependencies aren't resolved. 
E.g. in the sample provided below, the global ui5 installation of the _Business Application Studio_ is used (v2) instead of the local ui5 dev dependency (v3).

Please provide the following info:

  - MBT Version: 1.2.23
  - OS Version: BAS 

Steps to Reproduce:
> `package.json` (excerpt) in root of npm workspaces project
```json
{
  "workspaces": [
    "./packages/approuter",
    "./packages/html5"
 ]
}
```

> `mta.yml` (excerpt)
```yml
  - name: ui5app
    type: html5
    path: .
    build-parameters:
      build-result: dist
      builder: custom
      commands:
        - npm run build:ui5:cf -w html5
      supported-platforms: []
```
