### ISSUE TITLE
support for multiple processes

### ISSUE THREAD

**Issue by adamko147** [SAP/cloud-mta-build-tool#1076]
Dear MTA team,

is there a plan that MTA supports `processes` for CF apps, as it supported by CF manifests see https://docs.cloudfoundry.org/devguide/multiple-processes.html#manifest ?

I couldn't identify where is the issue. I have an manifest.yaml 
```yaml
---
applications:
- name: app
  path: .
  buildpacks:
  - nodejs_buildpack
  processes:
  - type: web
    command: node server.js
  - type: worker
    command: node worker.js
    health-check-type: process
    instances: 1
```
and `cf push` works as expected.

With following mta.yaml
```yaml
_schema-version: "3.3"
ID: app
version: 1.0.0

modules:
  - name: app
    type: nodejs
    path: .
    build-parameters:
      ignore:
      - mta_archives/
    parameters:
      processes:
        - type: web
          command: node server.js
        - type: worker
          command: node worker.js
          health-check-type: process
          instances: 1
```
and deploying using 
```sh
mbt build 
cf deploy mta_archives/app_1.0.0.mtar
```
The application has only web process (no worker).

Thanks,
Adam
