### ISSUE TITLE
Module route protocol support

### ISSUE THREAD

**Issue by adamko147** [SAP/cloud-mta-build-tool#1083]
Hello, 

when deploying grpc/http2 using mta.yaml, the protocol attribute on route is ignored, while it's working with manifest.yaml. Based on https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#routes the available options for protocol are `http1`, `http2` and `tcp`

Following manifest works well
```yaml
---
applications:
- name: test-grpc
  port: 8080
  routes:
  - route: test-grpc-mf.cfapps.us10.hana.ondemand.com
    protocol: http2
  health-check-type: process
  buildpacks:
  - binary_buildpack
  command: ./grpcserver
```

while similar with mta.yaml won't work
```yaml
_schema-version: 3.3.0
ID: test-grpc
version: 1.0.0

modules:
  - name: test-grpc
    type: binary
    path: .
    parameters:
      command: ./grpcserver
      routes:
        - route: test-grpc-mta.cfapps.us10.hana.ondemand.com
          protocol: http2
```

Is there any chance / plan to support protocol in mbt toolchain? 

Thank you,
Adam
