### ISSUE TITLE
support for readiness-health-check-*

### ISSUE THREAD

**Issue by sjvans** [SAP/cloud-mta-build-tool#1147]
`<module>.parameters.health-check-*` are already supported, as described [here](https://help.sap.com/docs/SAP_HANA_PLATFORM/cf8b4c5847374960a68b55cb86eae013/4050fee4c469498ebc31b10f2ae15ff2.html?version=2.0.07#parameters).

[`readiness-health-check-*`](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#readiness-health-check-type) should also be supported.

**Comment by sjvans** [comment]
hi @yutaoj 

thanks for the info, i'll check again. if they are supported, then they should probably be added to https://help.sap.com/docs/SAP_HANA_PLATFORM/cf8b4c5847374960a68b55cb86eae013/4050fee4c469498ebc31b10f2ae15ff2.html?version=2.0.07#parameters

best,
sebastian

**Comment by sjvans** [comment]
hi @yutaoj 

i checked again and the following mta does not produce a readiness check:
```
---
_schema-version: 3.3.0
ID: foobar
version: 1.0.0
modules:
  - name: foobar
    path: ./
    type: nodejs
    parameters:
      buildpacks:
      - nodejs_buildpack
      health-check-type: http
      health-check-http-endpoint: /healthy
      readiness-health-check-type: http
      readiness-health-check-http-endpoint: /ready
      readiness-health-check-interval: 10
```

further, via `cf create-app-manifest foobar`, i get a manifest with:
```
  processes:
  - type: web
    instances: 1
    memory: 1024M
    disk_quota: 1024M
    log-rate-limit-per-second: -1
    health-check-type: http
    health-check-http-endpoint: "/healthy"
    readiness-health-check-type: process
```

so something get's lost.

if i need to reach out to somebody else, please point me there.

thanks and best,
sebastian
