### ISSUE TITLE
How to use Zip builder?

### ISSUE THREAD

**Issue by swayongshen** [SAP/cloud-mta-build-tool#1159]
Hi all,

I've spent quite some time getting Zip builder to work, but it does not generate any visible output. This is the config, we are building a Javascript application into `./visualexecution/dist` and I'm iterating towards getting the `dist` folder to be zipped into `uideployer/dsc-visual-execution.zip`.  Currently stuck as the `dsc-visual-execution-zipped` does not produce a `zip` file anywhere.

Feel free to ping me on teams as well: yong.shen.swa

```
---
ID: ****
_schema-version: '3.1'
parameters:
  deploy_mode: html5-repo
version: 5.0.0

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm i -g bun
        - mkdir -p uideployer

modules:
  - name: dsc-vi-ui-deployer
    path: uideployer
    type: com.sap.application.content
    requires:
      - name: vi-model-ui-repo
        parameters:
          content-target: true
    build-parameters:
      requires:
        - name: dsc-visual-execution-zipped
          artifacts:
            - './*'
          target-path: 'dsc-visual-execution.zip'
  - name: dsc-visual-execution-zipped
    type: nodejs
    path: visualexecution/dist
    build-parameters:
      builder: zip
      requires:
        - name: dsc-visual-execution
  - name: dsc-visual-execution
    type: html5
    path: visualexecution
    build-parameters:
      supported-platforms: []
      builder: custom
      commands:
        - bun install
        - bun run build
        - cp xs-app.json dist/xs-app.json
      build-result: dist
resources:
  - name: ******
    parameters:
      service-plan: app-host
      service: html5-apps-repo
    type: org.cloudfoundry.managed-service

```
