### ISSUE TITLE
IAS based destination creation - unexpected error

### ISSUE THREAD

**Issue by PabloStockhausen** [SAP/cloud-mta-build-tool#1171]
I'm currently working on automating the creation of a destination for my SAP CAP service through an MTA build process, but I'm encountering difficulties with configuring the MTA descriptor correctly in regards to the destination service.
 
My CAP service is bound to an IAS instance, which is why I require my destination to be also be bound to the IAS service. When I reuse this service reference in my destination content deployment I am getting this error:

```bash
#2025 06 10 07:34:49.349#Z#DEBUG#destination-content#flowable-async-job-executor-thread-8885
#[SynchronousContentDeployStep] [destination-content] [ERROR] Unexpected error occured.
##2025 06 10 07:34:52.860#Z#DEBUG#....destination-content_code-mate-destination
#flowable-async-job-executor-thread-8905#[SynchronousContentDeployStep] [destination-content] [ERROR] Unexpected error occured.# 
```

Has anyone dealt with a similar scenario or can provide guidance on how to resolve this issue?

Below is an example of the MTA manifest that illustrates where I'm facing challenges:

```yaml
_schema-version: 3.3.0
ID: example-mta
version: 0.1.0
description: "Example MTA"

parameters: 
  enable-parallel-deployments: true

# =========================
# Modules
# =========================
modules: 
  - name: some-cap-service-srv
    type: application
    parameters: 
      docker: 
        ...
      instances: 1 
      routes: 
        - route: "${protocol}://${default-host}.internal.${default-domain}"
    provides: 
      - name: some-cap-service-api
        properties: 
          srv-url: "${protocol}://${default-host}.internal.${default-domain}"
    build-parameters: 
      no-source: true
    requires: 
      - name: destination-service
      - name: identity-service
        parameters: 
          config: 
            app-identifier: example-srv
  - name: destination-content
    type: com.sap.application.content
    build-parameters: 
      no-source: true
    requires: 
      - name: some-cap-service-api
      - name: identity-service
        parameters: 
          service-key: 
            name: identity-sk
      - name: destination-service
        parameters: 
          content-target: true
    parameters: 
      content: 
        instance: 
          existing_destinations_policy: update
          destinations: 
            - Name: some-cap-service-srv
              URL: ~{some-cap-service-api/srv-url}
              Description: Some CAP Service Destination
              ServiceInstanceName: identity-service
              ServiceKeyName: identity-sk

# =========================
# Resources
# =========================
resources: 
  - name: destination-service
    type: org.cloudfoundry.managed-service
    parameters: 
      service: destination
      service-plan: lite
  - name: identity-service
    type: org.cloudfoundry.managed-service
    parameters: 
      service: identity
      service-plan: application
      config: 
        display-name: identity-service-${space}
        xsuaa-cross-consumption: true
        credential-types: ["x509","client_credentials"]
        multi-tenant: false
        oauth2-configuration: 
          redirect-uris: 
            - https://*.${default-domain}/login/callback?authType=ias
            - https://*.${default-domain}/login/callback
          post-logout-redirect-uris: 
            - https://*.${default-domain}/*/logout.html
```
