### ISSUE TITLE
MTAR fetcher builder issue

### ISSUE THREAD

**Issue by NagarjunaVanapalli** [SAP/cloud-mta-build-tool#488]
- MBT Version: MBT version v0.2.12
  - OS Version: macOS Mojave (10.14.5)
 
While trying to do mta build encountering the issue. 

Error:

<img width="1324" alt="fetcherissue" src="https://user-images.githubusercontent.com/18714469/62708664-7912db00-ba11-11e9-93b9-4266120ff0ec.png">

Command used to build : mbt build -p=cf

**mta.yml config file :**
---
```
_schema-version: 3.1
ID: policy-service
version: 1.0.0
 
 
modules:
 
- name: mtar-les-admin-objectstore
  type: java
  path: policy/objectstore/
  parameters:
    buildpack: sap_java_buildpack
  build-parameters:
   builder: fetcher
   fetcher-opts:
         repo-type: maven
         repo-coordinates: com.sap.iot.edgeservices:onboard:3.1909.0 

```
