### ISSUE TITLE
False Positive during validation of deployment descriptor extension

### ISSUE THREAD

**Issue by sadros** [SAP/cloud-mta-build-tool#531]
- MBT Version: 0.3.2
  - OS Version: Win 10
  - If possible, provide a link to the project.
    (sap internal project) I can provide a link to a colleage via internal channels, though.

Steps to Reproduce:

1. Create a simple `mtad.yaml`
2. Create an `mtad.mtaext`
3. `mbt validate -s . -d dep -e mtad.mtaext`

Result:
> [2019-10-11 11:58:09]  INFO validating the MTA project
> [2019-10-11 11:58:10] ERROR the "mtad.mtaext" file is not valid:
> line 7: field type not found in type mta.ResourceExt

The mtaext schema specifies a `type` field for resources, though.

`mtad.yaml`
```yaml
_schema-version: "3.3"
ID: com.sap.example
version: 0.0.5
```

`mtad.mtaext`
```yaml
_schema-version: "3.3"
ID: com.sap.example.ext
extends: com.sap.example

resources:
  - name: example_resource
    type: org.cloudfoundry.managed-service
    parameters:
      service: some_service
      service-plan: some_plan
```

Regards
Sacha
