### ISSUE TITLE
NEO cli deploy-mta command fails after switch to Cloud MTA build tool 

### ISSUE THREAD

**Issue by taushanski** [SAP/cloud-mta-build-tool#630]
Hi Colleagues,

Due to the deprecation of MTA Archive builder tool we had to switch to the new Cloud MTA build tool. I did this yesterday following the migration guide here https://sap.github.io/cloud-mta-build-tool/migration/#features-that-are-handled-differently-in-the-cloud-mta-build-tool. So now the project is building fine and the mtar is being generated but when trying to deploy the generated mtar to SCP neo via NEO CLI [deploy-mta](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/1e12331df5e144c7b2cfa9f5db85d065.html) command it is failing with:

`
Deployment operation with id 'i10073' started.
11:49:05 Start deploying MTA archive 'com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar'
11:49:05 (!) ERROR: Deploying MTA archive 'com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar' failed: 'Invalid MTA archive [com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar].
 MTA deployment descriptor (META-INF/mtad.yaml) could not be parsed. 
For more information, see the troubleshooting section of the official documentation in the SAP Help Portal about resolving descriptor errors. Technical details: 
Invalid module [portal-deliveries] of type [com.sap.hcp.html5]: Parameter [name] is required and must have value.'
11:49:05 MTA archive 'com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar' deployment finished
`
The strange thing is that the module name is exactly the same as before when the deployment was working when the mtar was built with the old tool.

For completeness i am passting the content of mta.yaml file old and new version:

* old

```yaml
_schema-version: "2.1"
ID: com.sap.ibso.daikin.portal.deliveries
version: 1.0.0
description: "Portal app for viewing deliveries information."

parameters:
  hcp-deployer-version: "1.1.0"

modules:
  - name: "portal-deliveries"
    type: html5
    path: .
    parameters:
      version: 1.0.0-${timestamp}
    build-parameters:
      builder: grunt
      grunt-opts:
        - test
        - --code-coverage
        - --force
        - build
        - regex-replace
      build-result: dist/portal-deliveries
```

* new

```yaml
_schema-version: "2.1"
ID: com.sap.ibso.daikin.portal.deliveries
version: 1.0.0
description: "Portal app for viewing deliveries information."

parameters:
  hcp-deployer-version: "1.1.0"

modules:
  - name: "portal-deliveries"
    type: html5
    path: .
    parameters:
      version: 1.0.0-${timestamp}
    build-parameters:
      builder: custom
      commands:
        - npm install
        - grunt test --code-coverage --force build regex-replace
        - npm prune --production
      build-result: dist
```

Could you please advice what could be the issue here?
