### ISSUE TITLE
UAA instance not configured properly if multiple UAA instances refer to the same xs-security.json

### ISSUE THREAD

**Issue by romanisb** [SAP/cloud-mta-build-tool#677]
Bug-Report

- MBT Version: 1.0.8
- OS Version: Windows 10 x64, Building with WSL on Ubuntu 18.04.3 LTS
- Internal project. I can provide you a link per mail if needed.

Hello colleagues,

we have a project in which two uaa instances are created. Both instances use the same xs-security.json file. With the legacy mta archive builder, the configuration from the xs-security.json were merged into the mtad.yaml respectively. With cloud mbt the xs-security.json is now put into the archive file and is referenced in the MANIFEST.ML:

```
Name: xs-security.json
MTA-Resource: broker-uaa
Content-Type: application/json


Name: xs-security.json
MTA-Resource: ui-uaa
Content-Type: application/json
```

However, during a cloud foundry mta deployment one of the uaa instances will not be configured. Based in the order of the resource definition in the mta.yaml. The last one will be configured properly.

mta.yaml (snippet):
```
...
resources:
 - name: broker-uaa
   type: com.sap.xs.uaa
   parameters:
     service-plan: broker
     path: ./xs-security-broker.json
 - name: ui-uaa
   type: com.sap.xs.uaa
   parameters:
     service-plan: application
     path: ./xs-security.json
     config:
       tenant-mode: shared
...
```

Current workaround is to use a duplicate xs-security.json with a different name. But that is redundant and error prone.
