### ISSUE TITLE
Migration to MBT v2: what to do with mtad.yaml

### ISSUE THREAD

**Issue by marinho** [SAP/cloud-mta-build-tool#678]
This is neither a feature nor a bug, but rather a question on how to solve an issue. As I couldn't find neither a Slack channel nor a similar mean, I'm falling back in here.

I'm currently migrating to MBT v2 by following [this article](https://sap.github.io/cloud-mta-build-tool/migration/#features-that-are-handled-differently-in-the-cloud-mta-build-tool).

I moved a module of type "com.sap.html5.application-content" into a just created `mtad.yaml`, that looks like the following:

```
_schema-version: '3.3.0'
ID: com.sap.my-app-path
version: 1.8.0-SNAPSHOT
modules:
  - name: my-app-deployer
    type: com.sap.html5.application-content
    parameters:
      memory: 256M
      path: deployer
    build-parameters:
      type: com.sap.html5.application-content
      builder: grunt
      requires:
        - name: my-app
    requires:
      - name: my-app-app-host
```

But I don't know what more I should do with this `mtad.yaml`, as I couldn't find any documentation regarding to how to enable it so it's used during building. For instance: should I setup anywhere to call `mbt assemble`? Should we add some variable or another configuration? It's unclear how to "give life" to this file in my build pipeline.

- MBT Version: 2+
- OS Version: Linux used xMake Nova
- Link to the project: this is a SAP internal project. I can provide link via private message.
