### ISSUE TITLE
CDS build generated service views are not packaged in mtar

### ISSUE THREAD

**Issue by lindeengineering** [SAP/cloud-mta-build-tool#797]
Do you want to request a feature or report a bug?

bug

Please provide the following info:

  - MBT Version: 'mtaBuild' with docker image 'devxci/mbtci:1.0.16.1'
  - OS Version: sap piperlib
  - If possible, provide a link to the project.

Steps to Reproduce:

1. create cap project based on nodejs
2. create mtar

after creating the mtar the generated files in "db/gen" are not part of the mtar.

**Comment by lindeengineering** [comment]
cds build generates the files:

![image](https://user-images.githubusercontent.com/71772455/97665578-12e20000-1a7c-11eb-8143-35107de55366.png)

extracted mtar does not contain the gen folder:

![image](https://user-images.githubusercontent.com/71772455/97665622-3907a000-1a7c-11eb-9def-668216cbf3f6.png)

**Comment by katunin-ng** [comment]
@lindeengineering, Could you please share the mta.yaml file of your project?
Thank you
Natalia

**Comment by lindeengineering** [comment]
> @lindeengineering, Could you please share the mta.yaml file of your project?
> Thank you
> Natalia

```
ID: bb_be_revisioncorrection
_schema-version: "2.1"
version: 9.5.2
modules:
  - name: bb_be_revisioncorrection-db
    type: hdb
    path: db
    parameters:
      memory: 256M
      disk-quota: 512M
    requires:
      - name: bb_be_revisioncorrection-db-hdi-container
        properties:
          TARGET_CONTAINER: ~{hdi-container-name}
      - name: cross-container-service-appr
        group: SERVICE_REPLACEMENTS
        properties:
          key: appr-db
          service: ~{the-service-name}
  - name: bb_be_revisioncorrection-srv
    type: nodejs
    path: srv
    parameters:
      memory: 512M
      disk-quota: 512M
    provides:
      - name: srv_api
        properties:
          url: ${default-url}
    requires:
      - name: bb_be_revisioncorrection-db-hdi-container
resources:
  - name: bb_be_revisioncorrection-db-hdi-container
    type: com.sap.xs.hdi-container
    properties:
      hdi-container-name: ${service-name}
  - name: cross-container-service-appr
    parameters:
       service-name: hdi_BB_DB_APPR
    properties:
       the-service-name: ${service-name}
    type: org.cloudfoundry.existing-service
````
