### ISSUE TITLE
mbt provide modules --with-metadata

### ISSUE THREAD

**Issue by andre68723** [SAP/cloud-mta-build-tool#846]
We're using the mbt in a mixed environment with Java and Node. 

While from a deployment perspective everything works fine, the DevOps perspective misses a very essential part in form of a usable metadate-file for builds.

Example-MTAD.yaml for CAP:
```
  - name: myproduct-srv
    type: java
    path: srv
    properties:
      SPRING_PROFILES_ACTIVE: cloud
    build-parameters:
      builder: custom
      commands: [mvn clean package]
      build-result: "target/*.[wj]ar"

  - name: myproduct-db-deployer
    type: hdb
    path: db

  - name: myproduct-approuter
    type: nodejs
    path: app
```

Now for Java development, the pom.xml contains additional modules for e.g. 
* `integration-tests`
* `report-aggregate`

Same for Node or any other languages, there are further specifics maintained in the language-specific dependency file
which are needed for dev, but not for delivery/deploy (as modeled in mbt)

This leads to diverging picture and lots of additional effort for CD pipelines as they
always include additional tooling, e.g.
* Whitesource
* Fortify

This susequent tooling cannot handle anything defined in ´mta.yaml´ and instead use the pom.xml/package.json and similar. This leads to double maintenance, as all the non-delivery relevant modules (which are ignored by mbt correctly) need to be explicitly disabled and configured.

What is missing here is something like mbt provide modules with type in a machine readable format

**Current behaviour**
```
mbt init
mbt provide modules
[myproduct-srv myproduct-db-deployer myproduct-approuter]
```

**Expected behavior**
```
mbt init
mbt provide modules --with-metadata
[
    { "name":"myproduct-srv", "nativeType":"java", path "srv/" },
    { "name":"myproduct-db-deployer",  "nativeType":"nodejs", path "db/"},
    { "name":"myproduct-approuter",  "nativeType":"nodejs", path "app/"},
]
```

Can you please provide this additional output? This will make a huge difference and as part of this information is already avaiable via mbt provide modules, I assume this would not be a giant effort to extend it but would make a huge difference on consuming this programmatically.

Thanks! 
Andre
