### ISSUE TITLE
Build of MTA with module that provides service with properties

### ISSUE THREAD

**Issue by HeneryHawk** [SAP/cloud-mta-build-tool#870]
Hi
I created a mta.yaml, which should provide a module publicly, so that this module can be consumed again in another MTA. Following is a shortened version of the mta.yaml
```yaml
ID: provider
version: 0.1.0
description: some description
_schema-version: "3.1"
modules:
  - name: some-module
    type: nodejs
    path: path/to/module
    parameters:
      disk-quota: 256M
      memory: 128M
    build-parameters:
      ignore: ["default-env.json", "node_modules/"]
    provides:
      - name: some-module-public-endpoint
        public: true
        properties:
          url: ${default-url}
        parameters:
          visibility:          
            - org: ${org}
              space: "*"
```

According to the [documentation](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/b8e1953a618e47e1bd3c3a60c213226e.html), visibility of the public module can be restricted with the visibility parameter.
However, if I use this parameter, I get the following error.

```
Error: could not generate the "Makefile_20210603102339.mta" file: the "/home/project/mta.yaml" file is not a valid MTA descriptor: yaml: unmarshal errors:
  line 82: field parameters not found in type mta.Provides
```

For testing I created a mtad.yaml with `mbt mtad-gen` and executed the build (`mbt assemble`), but again I get the same error.
```
ERROR could not copy MTA artifacts to assemble: could not copy the MTA content: the "/home/project/mtad.yaml" file is not a valid MTA descriptor: yaml: unmarshal errors:
  line 54: field parameters not found in type mta.Provides
```

The line 82 / 54 is in each case the following:
```
parameters:
  visibility:          
    - org: ${org}
      space: "*"
```

Are parameters currently not supported with a provides definition?
Is the configuration correct (compared also a [sample repo](https://github.com/SAP-samples/cf-mta-examples/blob/main/cross-mta-configurations/provider/mtad.yaml#L19-L23))?

  - MBT Version: 1.2.1
  - OS Version: Ubuntu 18.04.5 LTS

Regards
Simon
