### ISSUE TITLE
Allow using parameters as variables in build-parameters

### ISSUE THREAD

**Issue by piejanssens** [SAP/cloud-mta-build-tool#907]
I have an mta.yaml and extension.mtaext:

```
  - name: my.app
    type: html5
    path: app
    parameters:
      memory: # set in mta ext
      buildEnv: # set in mta ext
    parameters-metadata:
      memory:
        optional: false
      buildEnv:
        optional: false
    build-parameters:
      ignore: ['node_modules/']
      builder: custom
      commands:
        - npm install
        - npm run build:${buildEnv}   
```

```
  - name: my.app
    parameters:
      memory: 128M
      buildEnv: demo
```

`mbt build -e extension.mtaext` results in `npm ERR! Missing script: "build:${buildEnv}"`
