### ISSUE TITLE
Improve Inclusion & Exclusion of Files & Folders

### ISSUE THREAD

**Issue by SchroederSteffen** [SAP/cloud-mta-build-tool#922]
Hi,

We're using MBT to build MTA archives for NestJS services (Node modules that have been transpiled from TypeScript using a custom builder).

By default, the built .mtar also contains the `src` & `test` folders and plenty of other project files like the `tsconfig.json`, its own Makefile (?) and more.
![image](https://user-images.githubusercontent.com/48728802/146574280-3089b293-3ce6-4f9e-93c5-ac23ae1aa2f2.png)

We're looking into ignoring the unnecessary files as [documented](https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-module-build-artifacts-to-package-into-mta-archive).
However, this will be quite cumbersome and will blow up the `mta.yaml`.

We would like to request either
- support for an `.mtaignore` file similar to `.gitignore` or `.npmignore` to achieve this in a cleaner fashion.
or
- support for a new `include` parameter instead of just a single `build-result` folder

Thanks and kind regards,
Steffen

**Comment by katunin-ng** [comment]
Hi Steffen,

As you mentioned the tool already provides a way to exclude files/folders from the result MTA archive - the 'ignore' build parameter). 
If you do not want to maintain these configurations in the mta.yaml to keep it more readable, please consider transferring the corresponding settings into a mta extension file and passing it during the build.

Regards
Natalia

**Comment by SchroederSteffen** [comment]
Hi Natalia,
Thanks for the response.

I've tested it with an MTA extension file and got it working.

I created a file called `.mtaignore` with the following content:
```
_schema-version: 3.3.0

ID: app-name.ignore
extends: app-name

modules:
  - name: app-name
    build-parameters:
      ignore:
        - .*
        - "*.db"
        - "*.mta"
        - coverage
        - postman
        - src
        - test
        - Jenkinsfile
        - jest.config.json
        - mta.yaml
        - nest-cli.json
        - renovate.json
        - sonar-project.properties
        - stryker.conf.json
        - tsconfig*.json
```

The result is an MTA archive with the following content:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/48728802/146947606-98260d6a-917e-4a6c-9529-79dc25bab4a4.png">

While this works, it's far from perfect. We would have to update the `.mtaignore` file every time a new root folder or file is added.

I think the alternative of having an `include` parameter would look much nicer:
```
_schema-version: 3.3.0

ID: app-name.ignore
extends: app-name

modules:
  - name: app-name
    build-parameters:
      include:
        - dist
        - node_modules
        - package*.json
```

This has also security aspects by avoiding embedding of secret files into your MTA etc.

Kind regards,
Steffen
