### ISSUE TITLE
allow building specific modules only (selective builds)

### ISSUE THREAD

**Issue by vobu** [SAP/cloud-mta-build-tool#945]
`mbt build` currently is an "all or nothing" build step - it will build all modules from `mta.yaml`.

Allowing to build a specific `module` from `mta.yaml` would save time (specifically in CI environments) and allow for faster deployment/test cycles.
Plus it would align nicely with `cf deploy` that allows for deploying specified modules only (`cf deploy mtar.mtar -m $module`).

suggestion: `mbt build --module $module`(as `-m` is already taken)
with `$module` being the `name` property of a module  from `mta.yaml`.

sample yaml:
```yaml
ID: app-4711
version: 0.0.1

# <snip />

modules:
  - name: ui
# <snip />
  - name: service 
# <snip />
  - name: db
# <snip />
```

sample build commands:
```shell
# build "service" module only
$> mbt build --module service
# build "ui" and "db" module only
$> mbt build --module ui,db

# and subsequently deploy 🎉 
$> cf deploy mtar.mtar -m ui,db
```

does that sound reasonable to whomever is listening here? 🤣
