### ISSUE TITLE
MBT Build Error CreateFile

### ISSUE THREAD

**Issue by tarun10ten** [SAP/cloud-mta-build-tool#977]
**### After executing the **mbt build** on vs code , I got the following error**
[2022-07-02 21:00:53]  INFO running the "after-all" build...
[2022-07-02 21:00:54]  INFO generating the metadata...
[2022-07-02 21:00:54] ERROR could not generate metadata when populating the manifest file: could not generate the manifest file when getting the artifact path of the "app_tarun-srv" module: CreateFile =\.app_tarun - Copy_mta_build_tmp\app_tarun-srv\data.zip: The system cannot find the path specified.
[2022-07-02 21:00:55]  INFO generating the MTA archive...
[2022-07-02 21:00:55]  INFO the MTA archive generated at: =\mta_archives\app_tarun_1.0.0.mtar
[2022-07-02 21:00:56]  INFO cleaning temporary files...

### If I try to deploy the generated mtar file I am getting the below error
FAILED
Could not get MTA ID from deployment descriptor: Could not get a valid MTA descriptor from archive

**mta.yaml**
```
---
_schema-version: '3.1'
ID: app_tarun
version: 1.0.0
description: "A simple CAP project."
parameters:
  enable-parallel-deployments: true
build-parameters:
  before-all:
   - builder: custom
     commands:
      - npm install --production
      - npx -p @sap/cds-dk cds build --production
      - npx rimraf gen/db/src/gen/data

modules:
  - name: app_tarun-srv
    type: nodejs
    path: gen/srv
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm-ci
    provides:
      - name: srv-api # required by consumers of CAP services (e.g. approuter)
        properties:
          srv-url: ${default-url}
    requires:
      - name: app_tarun-db

  - name: app_tarun-db-deployer
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    requires:
      - name: app_tarun-db

resources:
  - name: app_tarun-db
    type: com.sap.xs.hdi-container
    parameters:
      service: hana # or 'hanatrial' on trial landscapes
      service-plan: hdi-shared
```
